#:schema node_modules/@cloudflare/next-on-pages/.wrangler/config-schema.json
name = "veltrux-chordbook"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"
